# Generated by Django 5.0.6 on 2024-05-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='register_at',
            new_name='registered_at',
        ),
    ]
