# Generated by Django 5.0.6 on 2024-05-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('pos_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pos_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Part_Of_Speech',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('vocab_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vocab_en', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Vocabulary',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_vn', models.CharField(max_length=1000)),
                ('definition', models.TextField()),
                ('spelling', models.CharField(max_length=20)),
                ('example', models.TextField()),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabularies.partofspeech')),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabularies.vocabulary')),
            ],
            options={
                'db_table': 'Translation',
                'unique_together': {('vocab', 'pos')},
            },
        ),
        migrations.AddField(
            model_name='partofspeech',
            name='vocab',
            field=models.ManyToManyField(through='vocabularies.Translation', to='vocabularies.vocabulary'),
        ),
    ]
