# Generated by Django 5.0.6 on 2024-05-15 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVocab',
            fields=[
                ('myVocab_id', models.AutoField(primary_key=True, serialize=False)),
                ('vocab_en', models.CharField(max_length=1000)),
                ('vocab_vn', models.CharField(max_length=1000)),
                ('listVocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.listvocabulary')),
            ],
            options={
                'db_table': 'My_Vocabulary',
            },
        ),
    ]
